### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [67]:
# np.array
import numpy as np
a=np.array([1,2,3]) # vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]]) # matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # Tensor
print(c)  

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3] , dtype=bool)
np.array([1,2,3] , dtype=complex)
np.array([1,2,3] , dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11 , 2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
np.arange(1,11).reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((3,4))

array([[0.3664344 , 0.97420817, 0.95286421, 0.31171182],
       [0.90912611, 0.81407528, 0.45684677, 0.52553816],
       [0.37024549, 0.85288001, 0.92898359, 0.55682075]])

In [10]:
# np.linspace
np.linspace(-10 , 10 , 10)
# (lower-range , upper-range , no-of-elements)
# At equal distance 

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [12]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# ndim
a3.ndim

3

In [14]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
# itemsize
a2.itemsize

8

In [17]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


### Changing Datatype

In [18]:
# astype
a2.astype(np.int32)       

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

### Array Operations

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
# scalar operations

# arithmetic
a1 * 2 # All other eg. + , - , * , /
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational
a2 > 5 # Elementwise checking
# All relational operators eg. > , < , == , != , >= , <=
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# vector operations
# arithmetic
# Element wise operation
# All arithematic operators
a1 * a2 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [23]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[80., 31., 78.],
       [91.,  7., 24.],
       [28., 10., 88.]])

In [24]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.max(a1 , axis=1) # Applicable to all the functions

array([80., 91., 88.])

In [25]:
# mean/median/std/var
np.mean(a1 , axis=0)
np.median(a1)
np.std(a1) # standard deviation
np.var(a1) # variance

np.float64(1084.4691358024693)

In [26]:
# trigonomoetric functions
np.sin(a1)

array([[-0.99388865, -0.40403765,  0.51397846],
       [ 0.10598751,  0.6569866 , -0.90557836],
       [ 0.27090579, -0.54402111,  0.0353983 ]])

In [27]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [28]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[5.54062238e+34, 2.90488497e+13, 7.49841700e+33],
       [3.31740010e+39, 1.09663316e+03, 2.64891221e+10],
       [1.44625706e+12, 2.20264658e+04, 1.65163625e+38]])

In [29]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[16., 19., 75.],
       [48.,  6., 24.]])

### Indexing and Slicing

In [30]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a1
a1[-1]

np.int64(9)

In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a2[1,2]

np.int64(6)

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a3[1,0,1]

np.int64(5)

In [36]:
a3[0,1,0]

np.int64(2)

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1[2:5:2]

array([2, 4])

In [39]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [41]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [42]:
a2[1,::3]

array([4, 7])

In [43]:
a2[0,:]

array([0, 1, 2, 3])

In [44]:
a2[:,2]

array([ 2,  6, 10])

In [45]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [46]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [48]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [49]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [50]:
a1
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [53]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [55]:
for i in np.nditer(a3):  # use ravel internallly
    print(i)
a3

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Reshaping

In [56]:
# reshape

In [57]:
# Transpose
a2
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [58]:
# ravel
print(a3)
a3.ravel()

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [59]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5            

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [61]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [62]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [64]:
# vertical splitting

In [65]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]